version: '3'
services:
  home-assisstant:
    image: homeassistant/raspberrypi3-homeassistant:stable
    restart: always
    volumes:
      - /home/pi/home_assisstant:/config
    network_mode: host
    environment:
      TZ: 'Europe/Berlin'
  mqtt-broker:
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /home/pi/mosquitto/log:/mosquitto/log
      - /home/pi/mosquitto/config:/mosquitto/config/mosquitto.config
      - /home/pi/mosquitto/data:/mosquitto/data
