version: '3'
services:
  home-assisstant:
    image: homeassistant/raspberrypi3-homeassistant:stable
    volumes:
      - /home/pi/minikube/home_iot/home_assisstant:/config
    network_mode: host
    environment:
      TZ: 'Europe/Berlin'
  mqtt-broker:
    image: eclipse-mosquitto
    network_mode: host
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /mosquitto/log
