version: "3"

volumes:
  nextcloud:
  postgres-data:

services:
  app:
    image: nextcloud
    restart: always
    ports:
      - 8082:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=nextcloud_db_1
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGHOST=db
    depends_on:
      - db

  db:
    image: postgres:10.12-alpine
    restart: always
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
