version: '3.1'
services:
    jenkins:
        build:
            context: ./
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /home/egon/jenkins/:/var/jenkins_home
            - /home/egon/repos/home_iot/datarchiver/sort_pics/:/mnt/sort_pics
            - /home/egon/pics/:/mnt/pics
        ports:
            - "8080:8080"
            - "50000:50000"
