version: '3'
services:
  home-assisstant:
    image: homeassistant/home-assistant
    container_name: hass
    restart: always
    volumes:
      - ./home_assisstant:/config
    network_mode: host
    environment:
      TZ: 'Europe/Berlin'
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ../mosquitto/log:/mosquitto/log
      - ../mosquitto/config:/mosquitto/config
      - ../mosquitto/data:/mosquitto/data
