version: '3.6'
services:
  home-assisstant:
    image: homeassistant/home-assistant
    container_name: hass
    restart: always
    volumes:
      - ./home_assisstant:/config
    network_mode: host
    depends_on:
      - mqtt-broker
    environment:
      TZ: 'Europe/Berlin'
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt
    restart: always
    ports:
      - 1883:1883
    volumes:
      - ../mosquitto/log:/mosquitto/log
      - ../mosquitto/config:/mosquitto/config
      - ../mosquitto/data:/mosquitto/data
