version: '3'

services:
  sync2018:
    build: .
    image: megasync:latest
    tty: true
    volumes:
      - ./test_sync:/tmp
    environment:
      - MEGA_EMAIL=***678@gmx.de
      - MEGA_PWD=***
      - REMOTE_FOLDER=2018/a
      - LOCAL_FOLDER=/tmp
