# -----------------------------------------------
# path settings
# -----------------------------------------------
path_settings:
  dir_data_unsorted: /media/pi/egon/data_unsorted/
  dir_data_sorted: /media/pi/egon/data_sorted/
  exif_Executable: /usr/local/bin/exiftool

# -----------------------------------------------
# data formats
# -----------------------------------------------
pic_file_type:
  - jpg
  - JPG
  - jpeg
  - JPEG
  - png
  - PNG
vid_file_type:
  - mp4
  - MP4
  - avi
  - AVI
  - MTS
  - MOV

# -----------------------------------------------
# other
# -----------------------------------------------
exif_key_create_date: :CreateDate
daily_folder_suffix: _dummy